# Generated by Django 4.2.1 on 2023-05-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orders_count',
            field=models.IntegerField(default=0, verbose_name='orders count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
    ]
