# Generated by Django 4.2.1 on 2023-05-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('supplier', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('ordered_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_goods.product')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app_goods.shop')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
