# Generated by Django 4.2.1 on 2023-05-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_profile_discount_alter_profile_orders_count_and_more'),
        ('app_goods', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ordered_quantity',
            field=models.IntegerField(default=0, verbose_name='ordered_quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_goods.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app_goods.shop', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(max_length=200, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=200, verbose_name='delivery address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='app_goods.item', verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_users.profile', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
